# Choose the Image which has Node installed already
FROM node:14-alpine as dev-build
# set dockerignore file


# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
# ignore the .dockerignore file
COPY . .

VOLUME ./src ./src

# build app for production with minification
# RUN npm run build
CMD npm run serve


